// client/src/app/pages/login.component.ts
import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../core/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="auth-wrap">
      <form class="auth-card" (ngSubmit)="submit()" #f="ngForm">
        <div class="auth-mark">🍳</div>
        <h2>Kitchen QR</h2>
        <p class="muted">Sign in with your staff account.</p>
        <label class="field">
          <span>Username</span>
          <input name="username" [(ngModel)]="username" required autocomplete="username" autofocus />
        </label>
        <label class="field">
          <span>Password</span>
          <input name="password" type="password" [(ngModel)]="password" required autocomplete="current-password" />
        </label>
        <p class="error" *ngIf="error()">{{ error() }}</p>
        <button class="btn primary block" type="submit" [disabled]="busy() || !f.valid">
          {{ busy() ? 'Signing in…' : 'Sign in' }}
        </button>
      </form>
    </div>
  `,
})
export class LoginComponent {
  private auth = inject(AuthService);
  private router = inject(Router);

  username = '';
  password = '';
  busy = signal(false);
  error = signal<string | null>(null);

  async submit(): Promise<void> {
    this.busy.set(true);
    this.error.set(null);
    try {
      await this.auth.login(this.username.trim(), this.password);
      const role = this.auth.role;
      this.router.navigate([role === 'KITCHEN_STAFF' ? '/kitchen' : '/staff']);
    } catch (e: any) {
      this.error.set(e.message || 'Login failed');
    } finally {
      this.busy.set(false);
    }
  }
}

// client/src/pages/Login.tsx
import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { api, saveSession } from '../lib/api';

export default function Login() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const navigate = useNavigate();

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    setBusy(true);
    setError(null);
    try {
      const data = await api<{ token: string; user: any }>('/api/auth/login', {
        method: 'POST',
        body: JSON.stringify({ username, password }),
      });
      saveSession(data.token, data.user);
      navigate('/staff');
    } catch (e: any) {
      setError(e.message);
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="page">
      <div className="card" style={{ marginTop: 40 }}>
        <h1>Staff log in</h1>
        <p className="sub">Counter and kitchen staff sign in here.</p>
        {error && <div className="error">{error}</div>}
        <form onSubmit={submit}>
          <label className="field">
            <span>Username</span>
            <input value={username} onChange={(e) => setUsername(e.target.value)} autoComplete="username" />
          </label>
          <label className="field">
            <span>Password</span>
            <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} autoComplete="current-password" />
          </label>
          <button className="btn block" disabled={busy}>
            {busy ? 'Signing in…' : 'Log in'}
          </button>
        </form>
      </div>
      <p className="sub" style={{ textAlign: 'center' }}>
        <Link className="link" to="/">← Back to home</Link>
      </p>
    </div>
  );
}
