// client/src/app/pages/new-order.component.ts
import { Component, inject, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { ApiService } from '../core/api.service';
import { AuthService } from '../core/auth.service';
import type { CreatedOrder, MenuItem } from '../core/models';

interface CartLine {
  name: string;
  qty: number;
  unit_price: number; // cents
}

@Component({
  selector: 'app-new-order',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  template: `
    <div class="page-head">
      <div>
        <h2>New order</h2>
        <p class="muted">Add items, take payment, then share the QR code.</p>
      </div>
      <a class="btn ghost" routerLink="/staff">← Orders</a>
    </div>

    <!-- Step 1: build the order -->
    <div class="two-col" *ngIf="!created()">
      <div class="card">
        <h3>Menu</h3>
        <p class="error" *ngIf="error()">{{ error() }}</p>
        <div class="menu-list">
          <div class="menu-row" *ngFor="let m of menu()">
            <div><b>{{ m.name }}</b><div class="muted sm">{{ money(m.price) }}</div></div>
            <button class="btn sm" (click)="addMenu(m)">Add</button>
          </div>
          <p class="muted" *ngIf="!menu().length && !error()">No menu items yet.</p>
        </div>
        <h3 class="mt">Custom item</h3>
        <div class="inline-form">
          <input placeholder="Item name" [(ngModel)]="customName" />
          <input placeholder="$" inputmode="decimal" [(ngModel)]="customPrice" class="w-24" />
          <button class="btn sm" (click)="addCustom()" [disabled]="!customName.trim()">Add</button>
        </div>
      </div>

      <div class="card">
        <h3>Order</h3>
        <div class="cart" *ngIf="cart().length; else emptyCart">
          <div class="cart-row" *ngFor="let l of cart(); let i = index">
            <div class="cart-name">{{ l.name }}<div class="muted sm">{{ money(l.unit_price) }} each</div></div>
            <div class="qty">
              <button class="icon-btn" (click)="dec(i)">−</button>
              <span>{{ l.qty }}</span>
              <button class="icon-btn" (click)="inc(i)">＋</button>
            </div>
            <div class="cart-total">{{ money(l.qty * l.unit_price) }}</div>
          </div>
        </div>
        <ng-template #emptyCart><p class="muted">Cart is empty — add something from the menu.</p></ng-template>

        <div class="cart-grand" *ngIf="cart().length">
          <span>Total</span><b>{{ money(total()) }}</b>
        </div>

        <div class="mt" *ngIf="cart().length">
          <label class="field"><span>Customer name</span><input [(ngModel)]="customerName" placeholder="e.g. Priya" /></label>
          <label class="field"><span>Phone (optional)</span><input [(ngModel)]="customerPhone" inputmode="tel" /></label>
          <label class="field"><span>Notes (optional)</span><textarea [(ngModel)]="notes" rows="2"></textarea></label>
          <button class="btn primary block lg" (click)="submit()" [disabled]="busy()">
            {{ busy() ? 'Creating…' : 'Create order →' }}
          </button>
        </div>
      </div>
    </div>

    <!-- Step 2: payment -->
    <div class="card narrow" *ngIf="created() as c">
      <h3>Order #{{ c.order_number }} created</h3>
      <p class="big-total">{{ money(c.total_cents) }}</p>
      <div *ngIf="!paid()">
        <p class="muted">Take payment to activate the customer QR code.</p>
        <p class="error" *ngIf="error()">{{ error() }}</p>
        <div class="btn-row">
          <button class="btn primary" (click)="pay('cash')" [disabled]="busy()">💵 Cash</button>
          <button class="btn" *ngIf="c.demo_payments" (click)="pay('demo')" [disabled]="busy()">🧪 Demo card</button>
        </div>
        <a class="btn block mt" *ngIf="c.checkout_url" [href]="c.checkout_url" target="_blank" rel="noopener">
          💳 Pay by card (Stripe)
        </a>
        <p class="muted sm mt" *ngIf="c.demo_payments">Demo payments are for testing only.</p>
      </div>

      <!-- Step 3: QR code -->
      <div *ngIf="paid()">
        <div class="ok">✅ Payment confirmed — QR code is active.</div>
        <div class="qr-wrap">
          <img [src]="qrSrc()" alt="Order QR code" class="qr-img" />
        </div>
        <div class="btn-row">
          <a class="btn" [href]="qrSrc()" [download]="'order-' + c.order_number + '-qr.png'">⬇ Download</a>
          <button class="btn ghost" (click)="copyLink(c)">Copy tracking link</button>
        </div>
        <p class="muted sm mt" *ngIf="copied()">Link copied ✓</p>
        <a class="btn primary block mt" [routerLink]="['/staff/orders', orderId()]">Open order →</a>
      </div>
    </div>
  `,
})
export class NewOrderComponent {
  private api = inject(ApiService);
  private router = inject(Router);
  auth = inject(AuthService);

  menu = signal<MenuItem[]>([]);
  cart = signal<CartLine[]>([]);
  customName = '';
  customPrice = '';
  customerName = '';
  customerPhone = '';
  notes = '';
  busy = signal(false);
  error = signal<string | null>(null);
  created = signal<CreatedOrder | null>(null);
  orderId = signal<number | null>(null);
  paid = signal(false);
  copied = signal(false);

  total = computed(() => this.cart().reduce((s, l) => s + l.qty * l.unit_price, 0));
  qrSrc = computed(() => (this.orderId() ? this.api.qrUrl(this.orderId()!) : ''));

  constructor() {
    void this.loadMenu();
  }

  money(cents: number): string {
    return `$${(cents / 100).toFixed(2)}`;
  }

  private async loadMenu(): Promise<void> {
    try {
      this.menu.set(await this.api.get<MenuItem[]>('/api/menu'));
    } catch (e: any) {
      this.error.set(e.message);
    }
  }

  addMenu(m: MenuItem): void {
    this.addLine({ name: m.name, qty: 1, unit_price: m.price });
  }

  addCustom(): void {
    const name = this.customName.trim();
    const price = Math.round(parseFloat(this.customPrice) * 100);
    if (!name || !Number.isFinite(price) || price < 0) return;
    this.addLine({ name, qty: 1, unit_price: price });
    this.customName = '';
    this.customPrice = '';
  }

  private addLine(line: CartLine): void {
    const cart = [...this.cart()];
    const ix = cart.findIndex((l) => l.name === line.name && l.unit_price === line.unit_price);
    if (ix >= 0) cart[ix] = { ...cart[ix], qty: Math.min(99, cart[ix].qty + line.qty) };
    else cart.push(line);
    this.cart.set(cart);
  }

  inc(i: number): void {
    const cart = [...this.cart()];
    cart[i] = { ...cart[i], qty: Math.min(99, cart[i].qty + 1) };
    this.cart.set(cart);
  }

  dec(i: number): void {
    const cart = [...this.cart()];
    cart[i].qty -= 1;
    this.cart.set(cart.filter((l) => l.qty > 0));
  }

  async submit(): Promise<void> {
    this.busy.set(true);
    this.error.set(null);
    try {
      const c = await this.api.post<CreatedOrder>('/api/orders', {
        customer_name: this.customerName.trim() || undefined,
        customer_phone: this.customerPhone.trim() || undefined,
        special_instructions: this.notes.trim() || undefined,
        items: this.cart().map((l) => ({ name: l.name, qty: l.qty, unit_price: l.unit_price })),
      });
      this.created.set(c);
      this.orderId.set(c.id);
    } catch (e: any) {
      this.error.set(e.message);
    } finally {
      this.busy.set(false);
    }
  }

  async pay(kind: 'cash' | 'demo'): Promise<void> {
    const id = this.orderId();
    if (!id) return;
    this.busy.set(true);
    this.error.set(null);
    try {
      await this.api.post(`/api/orders/${id}/payments/${kind}`, {});
      this.paid.set(true);
    } catch (e: any) {
      this.error.set(e.message);
    } finally {
      this.busy.set(false);
    }
  }

  copyLink(c: CreatedOrder): void {
    const url = `${location.origin}/order/${c.public_token}`;
    navigator.clipboard?.writeText(url).then(
      () => this.copied.set(true),
      () => this.copied.set(false)
    );
  }
}

// client/src/pages/NewOrder.tsx
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { api, money } from '../lib/api';

interface MenuItem {
  id: number;
  name: string;
  price: number;
}

interface Line {
  name: string;
  qty: number;
  unit_price: number;
}

interface CreatedOrder {
  id: number;
  order_number: number;
  total_cents: number;
  checkout_url: string | null;
  stripe_configured: boolean;
  demo_payments: boolean;
}

export default function NewOrder() {
  const [menu, setMenu] = useState<MenuItem[]>([]);
  const [lines, setLines] = useState<Record<number, number>>({});
  const [customName, setCustomName] = useState('');
  const [customPrice, setCustomPrice] = useState('');
  const [customLines, setCustomLines] = useState<Line[]>([]);
  const [customerName, setCustomerName] = useState('');
  const [customerPhone, setCustomerPhone] = useState('');
  const [notes, setNotes] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [created, setCreated] = useState<CreatedOrder | null>(null);
  const navigate = useNavigate();

  useEffect(() => {
    api<MenuItem[]>('/api/menu').then(setMenu).catch((e) => setError(e.message));
  }, []);

  const setQty = (id: number, qty: number) => {
    setLines((prev) => {
      const next = { ...prev };
      if (qty <= 0) delete next[id];
      else next[id] = qty;
      return next;
    });
  };

  const addCustom = () => {
    const name = customName.trim();
    const price = Math.round(Number(customPrice) * 100);
    if (!name || !Number.isFinite(price) || price < 0) {
      setError('Enter a valid custom item name and price.');
      return;
    }
    setCustomLines((prev) => [...prev, { name, qty: 1, unit_price: price }]);
    setCustomName('');
    setCustomPrice('');
    setError(null);
  };

  const items: Line[] = [
    ...menu.filter((m) => lines[m.id]).map((m) => ({ name: m.name, qty: lines[m.id], unit_price: m.price })),
    ...customLines,
  ];
  const total = items.reduce((s, i) => s + i.qty * i.unit_price, 0);

  const submit = async () => {
    if (items.length === 0) {
      setError('Add at least one item.');
      return;
    }
    setBusy(true);
    setError(null);
    try {
      const data = await api<CreatedOrder>('/api/orders', {
        method: 'POST',
        body: JSON.stringify({
          customer_name: customerName.trim() || undefined,
          customer_phone: customerPhone.trim() || undefined,
          special_instructions: notes.trim() || undefined,
          items: items.map((i) => ({ name: i.name, qty: i.qty, unit_price: i.unit_price })),
        }),
      });
      setCreated(data);
    } catch (e: any) {
      setError(e.message);
    } finally {
      setBusy(false);
    }
  };

  const collectPayment = async (kind: 'cash' | 'demo') => {
    if (!created) return;
    setBusy(true);
    setError(null);
    try {
      const data = await api<{ warning?: string }>(`/api/orders/${created.id}/payments/${kind}`, {
        method: 'POST',
      });
      void data.warning;
      navigate(`/staff/orders/${created.id}`);
    } catch (e: any) {
      setError(e.message);
    } finally {
      setBusy(false);
    }
  };

  if (created) {
    return (
      <div className="page">
        <div className="card" style={{ textAlign: 'center', marginTop: 24 }}>
          <h1>Order #{created.order_number}</h1>
          <div className="big" style={{ fontSize: 34, fontWeight: 800, margin: '8px 0' }}>
            {money(created.total_cents)}
          </div>
          <p className="sub">Collect payment, then show the customer the QR code.</p>
          {error && <div className="error">{error}</div>}
          <div className="btn-row">
            {created.checkout_url && (
              <a className="btn" href={created.checkout_url} target="_blank" rel="noreferrer">
                💳 Pay by card (Stripe)
              </a>
            )}
            <button className="btn" disabled={busy} onClick={() => collectPayment('cash')}>
              💵 Cash received
            </button>
            {created.demo_payments && (
              <button className="btn warn" disabled={busy} onClick={() => collectPayment('demo')}>
                🧪 Demo card payment
              </button>
            )}
          </div>
          {!created.stripe_configured && (
            <p className="sub" style={{ marginTop: 12 }}>
              Stripe isn't configured — add STRIPE_SECRET_KEY to accept real card payments.
            </p>
          )}
          <div className="btn-row" style={{ marginTop: 16 }}>
            <button className="btn secondary" onClick={() => navigate(`/staff/orders/${created.id}`)}>
              View order →
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="page">
      <h1>New order</h1>
      <p className="sub">Enter the customer's items, then take payment.</p>
      {error && <div className="error">{error}</div>}

      <div className="card">
        <h2>Menu</h2>
        <div className="menu-grid">
          {menu.map((m) => (
            <div className="menu-item" key={m.id}>
              <div>
                <div className="name">{m.name}</div>
                <div className="price">{money(m.price)}</div>
              </div>
              <div className="qty">
                <button onClick={() => setQty(m.id, (lines[m.id] || 0) - 1)} aria-label="decrease">−</button>
                <b>{lines[m.id] || 0}</b>
                <button onClick={() => setQty(m.id, (lines[m.id] || 0) + 1)} aria-label="increase">+</button>
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="card">
        <h2>Custom item</h2>
        <div style={{ display: 'flex', gap: 8 }}>
          <input placeholder="Item name" value={customName} onChange={(e) => setCustomName(e.target.value)} />
          <input
            placeholder="$0.00"
            inputMode="decimal"
            style={{ maxWidth: 120 }}
            value={customPrice}
            onChange={(e) => setCustomPrice(e.target.value)}
          />
          <button className="btn secondary" onClick={addCustom}>Add</button>
        </div>
        {customLines.map((l, i) => (
          <div className="item-row" key={i}>
            <span>{l.name} <b>×{l.qty}</b></span>
            <span>
              {money(l.qty * l.unit_price)}{' '}
              <button className="link" style={{ border: 'none', background: 'none', cursor: 'pointer' }} onClick={() => setCustomLines((p) => p.filter((_, j) => j !== i))}>
                remove
              </button>
            </span>
          </div>
        ))}
      </div>

      <div className="card">
        <h2>Customer</h2>
        <label className="field">
          <span>Name (optional)</span>
          <input value={customerName} onChange={(e) => setCustomerName(e.target.value)} />
        </label>
        <label className="field">
          <span>Phone (optional)</span>
          <input value={customerPhone} onChange={(e) => setCustomerPhone(e.target.value)} inputMode="tel" />
        </label>
        <label className="field">
          <span>Special instructions</span>
          <textarea rows={2} value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="e.g. less spicy" />
        </label>
      </div>

      <div className="card">
        <div className="total-row">
          <span>Total</span>
          <span>{money(total)}</span>
        </div>
        <div className="btn-row">
          <button className="btn block" onClick={submit} disabled={busy || items.length === 0}>
            {busy ? 'Creating…' : `Create order · ${money(total)}`}
          </button>
        </div>
      </div>
    </div>
  );
}
