// client/src/pages/WaitlistAdmin.tsx
import { useCallback, useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { api, getToken, getUser } from '../lib/api';
import {
  WaitlistAdminEntry,
  WaitlistAdminLocation,
  WaitlistSummary,
  WAITLIST_STATUS_LABELS,
} from '../lib/waitlist';

/** Staff actions per entry status. Label + endpoint suffix. */
const ENTRY_ACTIONS: Record<string, { label: string; action: string; kind?: 'warn' | 'danger' }[]> = {
  WAITING: [
    { label: 'ALMOST READY', action: 'almost-ready' },
    { label: 'CALL', action: 'call' },
    { label: 'NO SHOW', action: 'no-show', kind: 'warn' },
    { label: 'CANCEL', action: 'cancel', kind: 'danger' },
  ],
  ALMOST_READY: [
    { label: 'CALL', action: 'call' },
    { label: 'SKIP', action: 'skip', kind: 'warn' },
    { label: 'NO SHOW', action: 'no-show', kind: 'warn' },
    { label: 'CANCEL', action: 'cancel', kind: 'danger' },
  ],
  CALLED: [
    { label: 'SEATED', action: 'seated' },
    { label: 'RECALL', action: 'recall' },
    { label: 'SKIP', action: 'skip', kind: 'warn' },
    { label: 'NO SHOW', action: 'no-show', kind: 'warn' },
    { label: 'CANCEL', action: 'cancel', kind: 'danger' },
  ],
  SKIPPED: [
    { label: 'MOVE BACK TO WAITING', action: 'restore' },
    { label: 'CALL', action: 'call' },
    { label: 'NO SHOW', action: 'no-show', kind: 'warn' },
    { label: 'CANCEL', action: 'cancel', kind: 'danger' },
  ],
};

export default function WaitlistAdmin() {
  const user = getUser();
  const [searchParams, setSearchParams] = useSearchParams();
  const [locations, setLocations] = useState<WaitlistAdminLocation[]>([]);
  const [locationId, setLocationId] = useState<number | null>(null);
  const [summary, setSummary] = useState<WaitlistSummary | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [busy, setBusy] = useState<string | null>(null);
  const [showSelectGuest, setShowSelectGuest] = useState(false);
  const [selectedGuestId, setSelectedGuestId] = useState<number | null>(null);
  const [showInactive, setShowInactive] = useState(false);
  const [inactiveEntries, setInactiveEntries] = useState<WaitlistAdminEntry[]>([]);

  const canMutate = user?.role === 'ADMIN' || user?.role === 'COUNTER_STAFF';

  // Load locations once.
  useEffect(() => {
    (async () => {
      try {
        const locs = await api<WaitlistAdminLocation[]>('/api/waitlist/admin/locations');
        setLocations(locs);
        const fromQuery = Number(searchParams.get('location_id'));
        const initial = locs.find((l) => l.id === fromQuery) || locs[0];
        setLocationId(initial ? initial.id : null);
        if (initial && !searchParams.get('location_id')) {
          setSearchParams({ location_id: String(initial.id) }, { replace: true });
        }
      } catch (e: any) {
        setError(e.message);
      }
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const loadSummary = useCallback(async () => {
    if (locationId == null) return;
    try {
      const s = await api<WaitlistSummary>(`/api/waitlist/admin/summary?location_id=${locationId}`);
      setSummary(s);
      setError(null);
    } catch (e: any) {
      setError(e.message);
    }
  }, [locationId]);

  const loadInactive = useCallback(async () => {
    if (locationId == null) return;
    try {
      const entries = await api<WaitlistAdminEntry[]>(
        `/api/waitlist/admin/entries?location_id=${locationId}&status=all`
      );
      setInactiveEntries(
        entries.filter((e) => !['WAITING', 'ALMOST_READY', 'CALLED', 'SKIPPED'].includes(e.status))
      );
    } catch (e: any) {
      setError(e.message);
    }
  }, [locationId]);

  // Initial + live summary refresh.
  useEffect(() => {
    loadSummary();
    if (locationId == null) return;
    let es: EventSource | null = null;
    try {
      const token = getToken();
      es = new EventSource(
        `/api/waitlist/admin/events?location_id=${locationId}&token=${encodeURIComponent(token || '')}`
      );
      es.addEventListener('waitlist', () => {
        loadSummary();
        if (showInactive) loadInactive();
      });
      es.onerror = () => es?.close();
    } catch {
      /* summary loads cover it */
    }
    return () => es?.close();
  }, [locationId, loadSummary, loadInactive, showInactive]);

  const pickLocation = (id: number) => {
    setLocationId(id);
    setSummary(null);
    setShowInactive(false);
    setShowSelectGuest(false);
    setNotice(null);
    setSearchParams({ location_id: String(id) }, { replace: true });
  };

  const mutate = async (action: string, entryId: number, busyKey: string) => {
    setBusy(busyKey);
    setNotice(null);
    setError(null);
    try {
      const res = await api<{ id: number; queue_number: string; status: string }>(
        `/api/waitlist/${entryId}/${action}`,
        { method: 'POST' }
      );
      setNotice(`${res.queue_number} → ${WAITLIST_STATUS_LABELS[res.status] || res.status}`);
      await loadSummary();
      if (showInactive) await loadInactive();
    } catch (e: any) {
      setError(e.message);
    } finally {
      setBusy(null);
    }
  };

  const callNext = async () => {
    if (locationId == null) return;
    setBusy('call-next');
    setNotice(null);
    setError(null);
    try {
      const res = await api<{ id: number; queue_number: string; status: string }>(
        '/api/waitlist/admin/call-next',
        { method: 'POST', body: JSON.stringify({ location_id: locationId }) }
      );
      setNotice(`Called ${res.queue_number}`);
      await loadSummary();
      if (showInactive) await loadInactive();
    } catch (e: any) {
      setError(e.message);
    } finally {
      setBusy(null);
    }
  };

  const activeLocation = locations.find((l) => l.id === locationId) || null;
  const entries = summary?.entries || [];
  const waitingEntries = entries.filter((e) => e.status === 'WAITING');
  const checkinDisplayUrl = activeLocation
    ? `${window.location.origin}/checkin/${activeLocation.slug}`
    : '';

  return (
    <div className="page wide">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 8 }}>
        <h1>Waiting List</h1>
        {!canMutate && (
          <div className="info" style={{ margin: 0 }}>
            View only — queue actions need an admin or counter-staff account.
          </div>
        )}
      </div>

      {locations.length > 0 && (
        <div className="filterbar">
          {locations.map((l) => (
            <button
              key={l.id}
              className={`chip${l.id === locationId ? ' active' : ''}`}
              onClick={() => pickLocation(l.id)}
            >
              {l.restaurant_name} · {l.name} ({l.active_count})
            </button>
          ))}
        </div>
      )}

      {error && <div className="error">{error}</div>}
      {notice && <div className="ok">{notice}</div>}

      {locationId == null ? (
        <div className="card empty">No locations found.</div>
      ) : !summary ? (
        <div className="card empty">Loading the waiting list…</div>
      ) : (
        <>
          <div className="card" style={{ textAlign: 'center' }}>
            <div className="sub" style={{ margin: 0 }}>NOW SERVING</div>
            <div className="qn-big">{summary.now_serving || '—'}</div>
            <div className="sub" style={{ marginBottom: 0 }}>
              NEXT UP:{' '}
              {summary.next_up.length > 0 ? summary.next_up.join(' · ') : '—'}
            </div>
          </div>

          <div className="btn-row" style={{ margin: '4px 0 12px' }}>
            <button
              className="btn"
              style={{ minHeight: 64, fontSize: 20 }}
              onClick={callNext}
              disabled={!canMutate || busy === 'call-next' || waitingEntries.length === 0}
            >
              {busy === 'call-next' ? 'Calling…' : '📢 CALL NEXT'}
            </button>
            <button
              className="btn secondary"
              style={{ minHeight: 64, fontSize: 20 }}
              onClick={() => {
                setSelectedGuestId(null);
                setShowSelectGuest(true);
              }}
              disabled={!canMutate || waitingEntries.length === 0}
            >
              SELECT GUEST
            </button>
          </div>

          <div className="card" style={{ padding: 8 }}>
            <h2 style={{ padding: '8px 8px 0' }}>Waiting ({entries.length})</h2>
            {entries.length === 0 ? (
              <div className="empty">Nobody waiting right now.</div>
            ) : (
              <table className="orders">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Guest</th>
                    <th>Party</th>
                    <th>Status</th>
                    <th>Waited</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {entries.map((e) => (
                    <tr key={e.id}>
                      <td>
                        <b>{e.queue_number}</b>
                      </td>
                      <td>
                        {e.customer_name}
                        {e.special_requirements && (
                          <div className="sub" style={{ margin: 0, fontSize: 12 }}>
                            {e.special_requirements}
                          </div>
                        )}
                      </td>
                      <td>{e.party_size}</td>
                      <td>
                        <span className={`badge ${e.status}`}>
                          {WAITLIST_STATUS_LABELS[e.status] || e.status}
                        </span>
                        {e.recall_count > 0 && (
                          <div className="sub" style={{ margin: 0, fontSize: 12 }}>
                            recalled ×{e.recall_count}
                          </div>
                        )}
                      </td>
                      <td>{e.waited_min} min</td>
                      <td>
                        <div className="btn-row" style={{ marginTop: 0, gap: 6 }}>
                          {(ENTRY_ACTIONS[e.status] || []).map((a) => (
                            <button
                              key={a.action}
                              className={`btn${a.kind ? ' ' + a.kind : ' secondary'}`}
                              style={{ minHeight: 36, padding: '6px 10px', fontSize: 12 }}
                              onClick={() => mutate(a.action, e.id, `${a.action}-${e.id}`)}
                              disabled={!canMutate || busy === `${a.action}-${e.id}`}
                            >
                              {a.label}
                            </button>
                          ))}
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>

          <div className="card">
            <h2>Restaurant check-in QR</h2>
            <p className="sub">
              Print this and place it at the entrance or host stand — customers scan it to join the waitlist.
            </p>
            <div className="qr-box">
              <img
                src={`/api/waitlist/location/${activeLocation?.slug}/qr.png`}
                alt="Restaurant check-in QR code"
              />
            </div>
            <div className="mono" style={{ marginTop: 12 }}>
              {checkinDisplayUrl}
            </div>
          </div>

          <div className="card">
            <button
              className="btn secondary block"
              onClick={() => {
                const next = !showInactive;
                setShowInactive(next);
                if (next) loadInactive();
              }}
            >
              {showInactive ? 'Hide completed entries' : 'Show completed entries'}
            </button>
            {showInactive && (
              <table className="orders" style={{ marginTop: 12 }}>
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Guest</th>
                    <th>Party</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {inactiveEntries.length === 0 ? (
                    <tr>
                      <td colSpan={4} className="empty">
                        No completed entries.
                      </td>
                    </tr>
                  ) : (
                    inactiveEntries.map((e) => (
                      <tr key={e.id}>
                        <td>
                          <b>{e.queue_number}</b>
                        </td>
                        <td>{e.customer_name}</td>
                        <td>{e.party_size}</td>
                        <td>
                          <span className={`badge ${e.status}`}>
                            {WAITLIST_STATUS_LABELS[e.status] || e.status}
                          </span>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            )}
          </div>
        </>
      )}

      {showSelectGuest && (
        <div className="modal-overlay" onClick={() => setShowSelectGuest(false)}>
          <div className="modal" onClick={(e) => e.stopPropagation()}>
            <h2>Select guest</h2>
            <p className="sub">Pick a waiting guest to call — useful when a table fits a particular party size.</p>
            {waitingEntries.map((e) => (
              <div
                key={e.id}
                className={`guest-pick${selectedGuestId === e.id ? ' selected' : ''}`}
                onClick={() => setSelectedGuestId(e.id)}
              >
                <b>{e.queue_number}</b>
                <span>
                  {e.customer_name} — {e.party_size} {e.party_size === 1 ? 'guest' : 'guests'}
                </span>
              </div>
            ))}
            <div className="btn-row">
              <button className="btn secondary" onClick={() => setShowSelectGuest(false)}>
                Close
              </button>
              <button
                className="btn"
                disabled={selectedGuestId == null || busy != null}
                onClick={async () => {
                  if (selectedGuestId == null) return;
                  await mutate('call', selectedGuestId, `call-${selectedGuestId}`);
                  setShowSelectGuest(false);
                }}
              >
                {busy ? 'Calling…' : 'CALL SELECTED'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// client/src/app/pages/waitlist-admin.component.ts
import { Component, inject, signal, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { ApiService } from '../core/api.service';
import { AuthService } from '../core/auth.service';
import type { WaitlistAdminEntry, WaitlistAdminLocation, WaitlistLocation, WaitlistSummary } from '../core/models';

function waitedLabel(iso: string): string {
  const m = Math.max(0, Math.floor((Date.now() - new Date(iso).getTime()) / 60000));
  if (m < 1) return 'just now';
  if (m < 60) return `${m}m`;
  return `${Math.floor(m / 60)}h ${m % 60}m`;
}

@Component({
  selector: 'app-waitlist-admin',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="page-head">
      <div>
        <h2>Waiting list</h2>
        <p class="muted">Live queue management <span class="live-dot"></span></p>
      </div>
      <label class="field" style="min-width:220px;margin:0" *ngIf="locations().length > 1">
        <span>Location</span>
        <select [ngModel]="locationId()" (ngModelChange)="pickLocation($event)">
          <option *ngFor="let l of locations()" [value]="l.id">
            {{ l.restaurant_name }} · {{ l.name }} ({{ l.active_count }})
          </option>
        </select>
      </label>
    </div>

    <p class="error" *ngIf="error()">{{ error() }}</p>
    <p class="muted" *ngIf="!summary() && !error()">Loading waiting list…</p>

    <ng-container *ngIf="summary() as s">
      <!-- Now serving / next up -->
      <div class="stat-row">
        <div class="stat">
          <span class="stat-lbl">Now serving</span>
          <span class="stat-num">{{ s.now_serving ?? '—' }}</span>
        </div>
        <div class="stat">
          <span class="stat-lbl">Next up</span>
          <span class="stat-num sm" style="font-size:1.1rem">{{ s.next_up.join(', ') || '—' }}</span>
        </div>
        <div class="stat">
          <span class="stat-lbl">Waiting</span>
          <span class="stat-num">{{ s.counts['WAITING'] ?? 0 }}</span>
        </div>
      </div>

      <div class="btn-row mb">
        <button class="btn primary lg" (click)="callNext()" [disabled]="!canMutate() || busy()">
          {{ busy() ? 'Calling…' : '📢 CALL NEXT' }}
        </button>
        <button class="btn lg" (click)="openPicker()" [disabled]="!canMutate() || !waitingEntries().length">
          👆 SELECT GUEST
        </button>
      </div>

      <!-- Serving now -->
      <div class="card" *ngIf="calledEntries().length">
        <h3>Now serving</h3>
        <div class="wl-rows">
          <div class="wl-row" *ngFor="let e of calledEntries()">
            <div class="wl-main">
              <b class="wl-qn">{{ e.queue_number }}</b>
              <span class="wl-name">{{ e.customer_name }}</span>
              <span class="muted sm">{{ e.party_size }} guests · waiting {{ waitedLabel(e.check_in_time) }}</span>
              <span class="pill st-CALLED" *ngIf="e.recall_count">recalled ×{{ e.recall_count }}</span>
            </div>
            <div class="wl-actions">
              <button class="btn sm primary" *ngIf="canMutate()" [disabled]="busyId() === e.id" (click)="mutate(e, 'seated')">Seated ✓</button>
              <button class="btn sm" *ngIf="canMutate()" [disabled]="busyId() === e.id" (click)="mutate(e, 'recall')">Recall</button>
              <button class="btn sm ghost" *ngIf="canMutate()" [disabled]="busyId() === e.id" (click)="mutate(e, 'skip')">Skip</button>
              <button class="btn sm ghost" *ngIf="canMutate()" [disabled]="busyId() === e.id" (click)="mutate(e, 'no-show')">No show</button>
              <button class="btn sm danger" *ngIf="canMutate()" [disabled]="busyId() === e.id" (click)="mutate(e, 'cancel')">Cancel</button>
            </div>
          </div>
        </div>
      </div>

      <!-- Waiting queue -->
      <div class="card">
        <h3>Waiting ({{ waitingEntries().length }})</h3>
        <div class="wl-rows" *ngIf="waitingEntries().length; else emptyTpl">
          <div class="wl-row" *ngFor="let e of waitingEntries()">
            <div class="wl-main">
              <b class="wl-qn">{{ e.queue_number }}</b>
              <span class="wl-name">{{ e.customer_name }}</span>
              <span class="muted sm">{{ e.party_size }} guests · waiting {{ waitedLabel(e.check_in_time) }}</span>
              <span class="pill" *ngIf="e.status === 'ALMOST_READY'">almost ready</span>
              <span class="muted sm" *ngIf="e.special_requirements">📝 {{ e.special_requirements }}</span>
            </div>
            <div class="wl-actions">
              <button class="btn sm" *ngIf="canMutate() && e.status === 'WAITING'" [disabled]="busyId() === e.id" (click)="mutate(e, 'almost-ready')">Almost ready</button>
              <button class="btn sm primary" *ngIf="canMutate()" [disabled]="busyId() === e.id" (click)="mutate(e, 'call')">Call</button>
              <button class="btn sm ghost" *ngIf="canMutate() && e.status === 'ALMOST_READY'" [disabled]="busyId() === e.id" (click)="mutate(e, 'skip')">Skip</button>
              <button class="btn sm ghost" *ngIf="canMutate()" [disabled]="busyId() === e.id" (click)="mutate(e, 'no-show')">No show</button>
              <button class="btn sm danger" *ngIf="canMutate()" [disabled]="busyId() === e.id" (click)="mutate(e, 'cancel')">Cancel</button>
            </div>
          </div>
        </div>
        <ng-template #emptyTpl><p class="muted">No one waiting right now.</p></ng-template>
      </div>

      <!-- Skipped -->
      <div class="card" *ngIf="skippedEntries().length">
        <h3>Skipped</h3>
        <div class="wl-rows">
          <div class="wl-row" *ngFor="let e of skippedEntries()">
            <div class="wl-main">
              <b class="wl-qn">{{ e.queue_number }}</b>
              <span class="wl-name">{{ e.customer_name }}</span>
              <span class="muted sm">{{ e.party_size }} guests</span>
            </div>
            <div class="wl-actions">
              <button class="btn sm" *ngIf="canMutate()" [disabled]="busyId() === e.id" (click)="mutate(e, 'restore')">Move back to waiting</button>
              <button class="btn sm primary" *ngIf="canMutate()" [disabled]="busyId() === e.id" (click)="mutate(e, 'call')">Call</button>
              <button class="btn sm ghost" *ngIf="canMutate()" [disabled]="busyId() === e.id" (click)="mutate(e, 'no-show')">No show</button>
              <button class="btn sm danger" *ngIf="canMutate()" [disabled]="busyId() === e.id" (click)="mutate(e, 'cancel')">Cancel</button>
            </div>
          </div>
        </div>
      </div>

      <!-- Restaurant check-in QR -->
      <div class="card" *ngIf="locationSlug()">
        <h3>Restaurant check-in QR</h3>
        <p class="muted sm">Print and display at the entrance — customers scan to join the waiting list.</p>
        <div class="qr-wrap">
          <img class="qr-img" [src]="restaurantQrUrl()" alt="Restaurant check-in QR code" />
        </div>
        <p class="muted sm" style="text-align:center;word-break:break-all">{{ checkinUrl() }}</p>
      </div>
    </ng-container>

    <!-- Select guest modal -->
    <div class="modal-backdrop" *ngIf="pickerOpen()">
      <div class="modal">
        <div class="modal-head">
          <h3>Select guest to call</h3>
          <button class="icon-btn" (click)="closePicker()">✕</button>
        </div>
        <div class="finish-options">
          <button
            *ngFor="let e of waitingEntries()"
            class="finish-opt"
            [class.selected]="selectedId() === e.id"
            (click)="selectedId.set(e.id)"
          >
            <span class="finish-emoji">🧍</span>
            <span class="finish-text">
              <span class="finish-label">{{ e.queue_number }} — {{ e.customer_name }}</span>
              <span class="finish-desc">{{ e.party_size }} guests · waiting {{ waitedLabel(e.check_in_time) }}</span>
            </span>
            <span class="finish-go">{{ selectedId() === e.id ? '●' : '○' }}</span>
          </button>
        </div>
        <p class="error" *ngIf="pickerError()">{{ pickerError() }}</p>
        <div class="btn-row">
          <button class="btn primary block" [disabled]="!selectedId() || busy()" (click)="callSelected()">
            {{ busy() ? 'Calling…' : '📢 CALL SELECTED' }}
          </button>
        </div>
      </div>
    </div>
  `,
})
export class WaitlistAdminComponent implements OnDestroy {
  private api = inject(ApiService);
  private route = inject(ActivatedRoute);
  auth = inject(AuthService);

  locations = signal<WaitlistAdminLocation[]>([]);
  locationId = signal<number | null>(null);
  summary = signal<WaitlistSummary | null>(null);
  error = signal<string | null>(null);
  busy = signal(false);
  busyId = signal<number | null>(null);
  private publicLocation = signal<WaitlistLocation | null>(null);

  pickerOpen = signal(false);
  selectedId = signal<number | null>(null);
  pickerError = signal<string | null>(null);

  private es: EventSource | null = null;

  waitedLabel = waitedLabel;

  constructor() {
    void this.init();
  }

  ngOnDestroy(): void {
    this.closeStream();
  }

  canMutate(): boolean {
    const r = this.auth.role;
    return r === 'ADMIN' || r === 'COUNTER_STAFF';
  }

  calledEntries(): WaitlistAdminEntry[] {
    return this.summary()?.entries.filter((e) => e.status === 'CALLED') ?? [];
  }

  waitingEntries(): WaitlistAdminEntry[] {
    return this.summary()?.entries.filter((e) => e.status === 'WAITING' || e.status === 'ALMOST_READY') ?? [];
  }

  skippedEntries(): WaitlistAdminEntry[] {
    return this.summary()?.entries.filter((e) => e.status === 'SKIPPED') ?? [];
  }

  locationSlug(): string {
    return this.locations().find((l) => l.id === this.locationId())?.slug ?? '';
  }

  restaurantQrUrl(): string {
    return `/api/waitlist/location/${encodeURIComponent(this.locationSlug())}/qr.png`;
  }

  checkinUrl(): string {
    return this.publicLocation()?.checkin_url ?? '';
  }

  pickLocation(id: number): void {
    this.locationId.set(Number(id));
    this.summary.set(null);
    void this.refresh();
    this.openStream();
  }

  private async init(): Promise<void> {
    try {
      const locs = await this.api.get<WaitlistAdminLocation[]>('/api/waitlist/admin/locations');
      this.locations.set(locs);
      const q = Number(this.route.snapshot.queryParamMap.get('location_id'));
      const first = locs.find((l) => l.id === q) ?? locs[0];
      if (!first) {
        this.error.set('No restaurant locations found for your organization.');
        return;
      }
      this.locationId.set(first.id);
      await this.refresh();
      this.openStream();
    } catch (e: any) {
      this.error.set(e.message || 'Could not load the waiting list.');
    }
  }

  private async refresh(): Promise<void> {
    const id = this.locationId();
    if (!id) return;
    try {
      const [s, pub] = await Promise.all([
        this.api.get<WaitlistSummary>(`/api/waitlist/admin/summary?location_id=${id}`),
        this.api
          .get<WaitlistLocation>(`/api/waitlist/location/${encodeURIComponent(this.locationSlug())}`)
          .catch(() => null),
      ]);
      this.summary.set(s);
      this.publicLocation.set(pub);
      this.error.set(null);
    } catch (e: any) {
      this.error.set(e.message || 'Could not load the waiting list.');
    }
  }

  private openStream(): void {
    this.closeStream();
    const id = this.locationId();
    if (!id) return;
    this.es = this.api.waitlistStaffEvents(id, () => void this.refresh());
  }

  private closeStream(): void {
    this.es?.close();
    this.es = null;
  }

  async callNext(): Promise<void> {
    const id = this.locationId();
    if (!id || !this.canMutate()) return;
    this.busy.set(true);
    this.error.set(null);
    try {
      await this.api.post('/api/waitlist/admin/call-next', { location_id: id });
      await this.refresh();
    } catch (e: any) {
      this.error.set(e.message || 'Could not call the next guest.');
    } finally {
      this.busy.set(false);
    }
  }

  openPicker(): void {
    this.selectedId.set(null);
    this.pickerError.set(null);
    this.pickerOpen.set(true);
  }

  closePicker(): void {
    this.pickerOpen.set(false);
  }

  async callSelected(): Promise<void> {
    const id = this.selectedId();
    if (!id || !this.canMutate()) return;
    this.busy.set(true);
    this.pickerError.set(null);
    try {
      await this.api.post(`/api/waitlist/${id}/call`, {});
      this.closePicker();
      await this.refresh();
    } catch (e: any) {
      this.pickerError.set(e.message || 'Could not call this guest.');
    } finally {
      this.busy.set(false);
    }
  }

  async mutate(e: WaitlistAdminEntry, action: string): Promise<void> {
    if (!this.canMutate()) return;
    if (action === 'cancel' && !confirm(`Cancel ${e.queue_number} (${e.customer_name})?`)) return;
    this.busyId.set(e.id);
    this.error.set(null);
    try {
      await this.api.post(`/api/waitlist/${e.id}/${action}`, {});
      await this.refresh();
    } catch (e2: any) {
      this.error.set(e2.message || 'Action failed.');
    } finally {
      this.busyId.set(null);
    }
  }
}
